// ignore_for_file: lines_longer_than_80_chars

// Unit tests for vault thumbnail generation.
//
// Platform-agnostic (VM + Chrome):
// 1. generateThumbnail for valid images → returns JPEG bytes
// 2. generateThumbnail for PDF/unsupported → null
// 3. generateThumbnail for corrupted bytes → null (no crash)
// 4. generateThumbnail for video > 200 MiB (bytes, no path) → null
// 5. generateThumbnail for invalid video bytes → null (no crash)
// 6. scaling — aspect ratio, degenerate, no-upscale, via decoding the output
// 7. pixel probes — sub-256 images keep real pixels (not white)
// 8. VideoSource create/dispose balance on every video attempt
// 9. path-based video: inaccessible path → null (no crash, no VideoSource)
//
// Chrome-only (skipped on VM):
// 10. real MP4 → JPEG thumbnail of the ~1s frame, not the first frame
// 11. path-based video: blob URL path → thumbnail, no VideoSource created
// 12. path-based video: bytes over the cap + path → thumbnail (no size reject)
//
// Run: flutter test --platform=chrome test/vault_thumbnail_test.dart
//      flutter test test/vault_thumbnail_test.dart

import 'dart:convert';
import 'dart:typed_data';

import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter_test/flutter_test.dart';
import 'package:get_thumbnail_video/index.dart' show ImageFormat;
import 'package:get_thumbnail_video/video_thumbnail.dart';
import 'package:image/image.dart' as img;

import 'package:bmo_app/core/platform/video_source.dart';
import 'package:bmo_app/features/vault/data/vault_thumbnail.dart';

import 'video_thumbnail_register.dart';

// ---------------------------------------------------------------------------
// Test data helpers (package:image — no browser APIs)
// ---------------------------------------------------------------------------

Uint8List _createJpeg(int width, int height, {img.Color? color}) {
  final image = img.Image(width: width, height: height, numChannels: 3);
  img.fill(image, color: color ?? img.ColorRgb8(68, 136, 204));
  return Uint8List.fromList(img.encodeJpg(image, quality: 90));
}

Uint8List _createPng(int width, int height, {img.Color? color}) {
  final image = img.Image(width: width, height: height, numChannels: 3);
  img.fill(image, color: color ?? img.ColorRgb8(68, 204, 136));
  return Uint8List.fromList(img.encodePng(image));
}

/// Two-frame animated GIF: red first frame, blue second.
Uint8List _createAnimatedGif(int width, int height) {
  final red = img.Image(width: width, height: height, numChannels: 3);
  img.fill(red, color: img.ColorRgb8(255, 40, 40));
  final blue = img.Image(width: width, height: height, numChannels: 3);
  img.fill(blue, color: img.ColorRgb8(40, 40, 255));

  final encoder = img.GifEncoder(repeat: 0);
  encoder.addFrame(red, duration: 10);
  encoder.addFrame(blue, duration: 10);
  return Uint8List.fromList(encoder.finish()!);
}

img.Image _decode(Uint8List bytes) => img.decodeImage(bytes)!;

img.Pixel _centerPixel(img.Image image) => image.getPixel(
      image.width ~/ 2,
      image.height ~/ 2,
    );

/// 2s 160x90 H.264 (12 fps) generated by AVAssetWriter. Background hue
/// sweeps per frame and a white block moves 5px/frame; the frame at t=1s is
/// visibly different from the first frame.
const String _kProbeMp4Base64 = 'AAAAHGZ0eXBtcDQyAAAAAWlzb21tcDQxbXA0MgAAA5Vtb292AAAAbG12aGQAAAAA5qu9S+arvUsAAAJYAAAEsAABAAABAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAADIXRyYWsAAABcdGtoZAAAAAHmq71L5qu9SwAAAAEAAAAAAAAEsAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAEAAAAAAoAAAAFoAAAAAACRlZHRzAAAAHGVsc3QAAAAAAAAAAQAABLAAAABkAAEAAAAAApltZGlhAAAAIG1kaGQAAAAA5qu9S+arvUsAAAJYAAAEsFXEAAAAAAAxaGRscgAAAAAAAAAAdmlkZQAAAAAAAAAAAAAAAENvcmUgTWVkaWEgVmlkZW8AAAACQG1pbmYAAAAUdm1oZAAAAAEAAAAAAAAAAAAAACRkaW5mAAAAHGRyZWYAAAAAAAAAAQAAAAx1cmwgAAAAAQAAAgBzdGJsAAAAoHN0c2QAAAAAAAAAAQAAAJBhdmMxAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAKAAWgBIAAAASAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGP//AAAAJmF2Y0MBZAAL/+EACydkAAusVlDDeEZEAQAEKO48sP34+AAAAAAKZmllbAEAAAAACmNocm0AAAAAABhzdHRzAAAAAAAAAAEAAAAYAAAAMgAAAGBjdHRzAAAAAAAAAAoAAAABAAAAZAAAAAEAAAD6AAAAAQAAAGQAAAABAAAAAAAAAAEAAAAyAAAAAQAAAPoAAAABAAAAZAAAAAEAAAAAAAAAAQAAADIAAAAPAAAAZAAAABRzdHNzAAAAAAAAAAEAAAABAAAAJHNkdHAAAAAAIBAQGBgQEBgYEBAQEBAQEBAQEBAQEBAQAAAAHHN0c2MAAAAAAAAAAQAAAAEAAAAMAAAAAQAAAHRzdHN6AAAAAAAAAAAAAAAYAAAA+wAAAOgAAADZAAAAzwAAALAAAADHAAAAwgAAAG8AAACaAAAAyQAAAH4AAACfAAAAsgAAAJsAAACNAAAAqgAAAJoAAADAAAAAvgAAAQ0AAADQAAAA1QAAAVAAAADuAAAAGHN0Y28AAAAAAAAAAgAAA8EAAAx0AAAAAW1kYXQAAAAAAAASTwAAADsGBTJHVkrcXExDP5TvxRE80UOoAQAAAwABAwAAAwABAgABOIALAAADAAADAAADAEYMA4kdAQ3/////gAAAALgluCAE/2O2fd4IJT8eBNiboyDAIz1gA86KAA0FusTtts6UenNPfyClkDJ184VYY3UM96HAuZG49rFbojm1OJygKH6BXVwqR76a12d//PmfQpalUlXZZ9LtnGHd4uh322hgII0iJFOIEOIpHYLXtwgCSEk9jKa7ItfwVNYBIHqM5bpT9oJEWfjUqI2TqEUubvKhaOF/Liyv2hJGCn4/iBoRZqi9ADtnlJWV2S2uIAH+b5CVOPnb/jq8AAAA5CHhEFf+PhDFyC+3/wdbPgtgmWIXF+6VIUzI1RLjX4RpT+Bu9j9I6yktSvxn8WEDkT7RT+NdZDFmtx2Hbiz+u1hNn2vFyDb36mrAsVfrrJg1RXSZ8HB9JRx/0uNf/AU7AZVNIWfuDy37tmu66UH5Ygc0ggdecPFc+KTZqTZHKUYjQ52EVFYEREX9KKvuwtab5fx1pPjNMKDCOIAmU7qoyekH4lgBndW/WexSOSHNV/EoIvimtxh/Su6TmbgsVcNE6UWMl6x1rWa0f5RWdG8fLjuOHgGugpdr/893wGuRHR4yjN268AAAANUhqIKH//S3uBkx+4pFQV0JODjpQaX+WDI/fShqUFGcn30M34eiAenpwpfSDbDBH2QRG9kSMfHX+ugvDkG+OqfefyvvSZba8PakMYeT/+nUIUeqvGpj8P9SCxtWXsjwaQyjhhEJPgZhHttnV+sp4jNMISCbS1fKwUvLiPWlKkODbSsJnT7VBXWwssqSopESg2MSGGo3YOGQ52PWjBK9PaE8/nlPhLjI0qaMQVdteaisz7trojX8CIGT/GiOR9LRvmvJnsinkVuHmvs43Lz5ME7v78k5M0AAAADLAajBiT/+2AYTr/QeBBylHZxUidCUzFbxAk+FcD389zJJxr79w76AkLoNltMXPHghhVr51R8Tj635n5UtypggN/PqfzpLB3QHuegFA+ZOb2t0TNYGxlfetGXmT/f7xqtfSJxzBtyr+9DgB4XKmybdheYXCOA2+VfOeg3EzYSq50sjQXRuPhf0kCEc1oP2GwjaMIleP9sqvhhPFlKhpP6VMi3eo9gz9LsO649Yzq5H76YWvNJ2nSuOIzaa/mX1/IgcDQDtXaWSJHQFFYgAAACsAajDiv/+3HgLftuMgAC1GZENHFAgg/AXM2ixlNn+y/i7wnYY+DiTQy17OIbNSIyNBzP18jViQotTmdSp0RzUnwUSs0yxkMj4nx28FunYIZSM+i7dNk+iHAXfEQUWPtfLAnB/oQo5Njwv9Mm9UbT87hB47Anx8H6EfwloMOl9yve6N6x2SOUVMRJ7gPaqDfuhPdU3uP51IqCxxgy0ht+2j6w6Zr9TUVgCGmoogAAAAMMh4yGiJf/+UwljZBTH//GDWwB8DizOXn0HvE2UvwlKfA0uDSQvRyYirvVMZVF2WqLhysIqyRlrRcB4LcLQZ6ZHmWMP5ici7ZibLRQq7jXqS4mzsC5MLCHzxmAA1x+EGV5TeALbsqAl/NBR6BZFcCSMBhjcw05ycfmBc3cqQpapjjaxVliOyABw/VWnb0O2VbCd7DYRvrxpOEwEvvh9z8Izv3Dyvjgmvp3e9njuXuoKXnTvwAMUpqir8SLOlLsiG5lQMUAAAAC+IakGhP/+26YLlxyrardvqBM19+mnwaAJAnttwgYJWWh5G/GJCzdJmAizHCUjua9tfEKGc/kfAeQDAOfcbgs6RjsmHFEpgvibuk/rxSMgkoD7y6zl6JLXdY9vnDeH4eLPAAAZXcKHZyrGwIOvEMmIwToM7UURf3NWzADOK4Bu+NdRAjYgxKmbQAHO6XHOVtcgZMgbOwAowkT5wl6sabUD+r+b33F2IcvEdi8GYAAQza3UcK4KgAE1OAAAAwFwRwAAAGsBqUWK/1jRwwqKw1pN4uNNeLo6gnxZNMKvl5LuXimVi+QxQuvU+/hwih0Udk4ND32PCcGgjdDPqG/JvE2Mk7roEb6bFxsUTbwSQOwtfFGz1pBmxTrRFDpeGfjztYIfF8+BvAEEniltGfqWIAAAAJYBqUeK//4+QZHiIiKGa8hXUST93zgpFbYOwk5P5eP+Mvu5iFqnKp/q5Y59gzrX8Q63HUe30xTqhAFItJC5PUAxLt3pm1S+d0XU2PgNM9uAS3v7temJQbPJsHClBQHGPnMowJcUlPsaYZnXrYgUL9532E6xpjpcPZdkL6K6o8JCyccdiyQyCykLrKKxkHr/wS+O/s9NfyAAAADFIeUloiJ/0wyBlHtzEQPa51P8Bnu3of8YHBbEeuUSPxVuKDV2afUrWLYjD6J9mSWT/yBYDdPnDY9VGjeLpatIGJ3/h/aZJLFGzd8PDzQrKChyWfggpvvc4l5Bo8qxrUnQdy5f9nfJ46WDgab8KM8zdvDY7xZn8tTx8AFyW/9giNHdUshpkPgc2lMoh3Fbwh8KQkvDZurtMiyAZQaRBHuVkm1jo9ZmdX5YJIwq0EtKFEPVj9hf5Cw0AOM1CokNu8EUqSaaS7AAAAB6IeYoT//XZ6GU32ng7v86fzqtVfR08zaXG4u7G16LobR7xT7xQlxbfgIxh8/qTdlT7Pg/eoeU321VBjbeRAMxZUV83Ifaema7/IX5pnPF4I+0V5IwuJJvWpNvxcLBPpbVjskOL3Aq2aJWpuccGP2A2UTGjygGvg7cg4AAAACbIecsT//XZ6GU32ng7v86fzqtVfR08zaXG4u7G16LobR7xT9bt8iXADTxwm6vYl9Fjb/vd/WiYhl3preYI0FxZSgufIimJLvTAkIGN7c/ZpnMwwGeAaIGZB0osKNAUyIPJrXGu28HOqwSTrNLEEBjh5PvBifQax87Ry0pGEYEpAjKPBgct/D+AOZycKUoD0DAL1kUXllNCJ8+iNIAAACuIegwT//XZ6GU32ng7v8PaEBJ98jrXM2lxuLuxtei6G0e8U/WpPwCEdQIO5YTWTjXvpqo7F2qm/T8dHSlwQrZCWP26fT2aqoodf1svsVofIK8/ROzaVNOXhF8iROOe6EX+vdgy6cjpX09/LzZ8ErEH0vug5g8vgi/Ht+bgZeOjqAlW+/ERfQM/kBLzwKDfwOBjSjHbRqRW0Jb3UCzGMFiQTvr/AtK2jCqoQiRJjDAAAAAlyHpNEv/s1FCyP5CvapJsPHzsnrnhOU8NWnCveHaj13u4qQWiPjiYy3mPPVf/CFzO5fROubQmuqm2ZfN5zuV/Oae8CXz3IlfOSAu5uoJusryRgN7RXl648w/EufAKEXseWeElA5fjmFze+owWPRvNSDxxIB3/JGirO/NwM9f69WLbRNEjtI4T3HDdT9/I+W1/YKQAW9AC0AAAACJIeo4S/+zUUW7Z+BwPH0RwRkX0VFQMoZDPB1Hrvd3QLfHSK79FTrGeUUtN/zAJxWKGkGLmwTiQAe5NECJpxS84Kbt6xoshb0Np8m+gjDZhx+v1yOs8A+g0PQiaAtiYQL0NNScS87KcuPRhIPOCyU8hyzPMrh20fKZVGbArGxj6gOJGEWhYVtqeEIAAACmIes8S/+zUULIvYRK/un+H1zwnKeGrThXvDtR673cVILQ2adlRJf7E+oZX4JpgeCWz5s7rWpH19h3t9cuP8V328xgUFeTCsYAW8C8OUE32bDRm5fi9sW1IneKqZq3jssQkS4rnojXWgtzuyClKoX8ao6gOnY6Ou/LGnaoF6lsButbPOtg5/l+87stECBkJBpDdNNMnFx7scbiST1oBxKpYuslIlQ2PQAAAJYh7EBP/9dnoZTfaeDu/w9ohbVvkda5m0uNxd2Nr0XUQsVPnZ+mW6BGVC7ovKGA2dj5PJbvYhgUwOm4iJRZCeUz7x76JQyRlA+cINv6Llh2jyyybWDpKSjx7ohr8VfyD2wp+SlPJQiqBtgT0Q6Fp1ErX0Bqx7R93xrD7+0Wvx+aoPcWAMR1AjtioMHb/X0h3DvCF3ejcdoAAAC8Ie1ERP/TDIMNu3Fv4y6C28ge7eh/xgcFsR65RI/FwxSl06Kdo9pbroFaTtnRdUj/aKchpuvrXzBYDWDhuDYjk9eN28626nq0CQhSVBiiD7XlsLvE2zI/hg+iBgJnE+xGXJZr0slGN3UfTVNARlcPnmVtMJW5LSeiTTtnoYREQ83HQs/yM/aKeHL7fMPFHau2pQSz58tLHDoC6zPXJKHXBkYXlq0KwvzQtAL9GXqqUgrarqITPpg5C0JpQFQAAAC6Ie5IRf9RzUW76WkcLheEcYZSvOz/Nwp3WU1u9CrxPr94WOjrA+9T0YM2HeH/letVlkCkVwDnNOsbg7zwsrRSQMUwoedbkVf1p+n/b4pjm/6AJF7UEyBkqpROJ13mHrHPwcB04bE3YDaJgar6ANl23NDCxOIMwA3pcAZCBYhXed/n7guEo2ChdUSIXOLu+DPgT0vUYjzJRomv4aIoMK/EdZT4bPn4rM8HvzdgMZTqYFeOF2d45ivOzBRAAAABCSHvTEX/VdGEFq4lXgsbBOGSgMeQ6DMLdDJQCiWSNYLQfOMA45oJdpCjNi3HTwNBrNs1S5yhtddGpuK53rqb/4oPYKHuV52W/V0QY9tWBQ6Xy7WZNqxY45WSeVJhF57HuzpMvk+4TEOCeHwYBE7IpOwAhqMGQzEDMBwysp2PVk4vm00ApouZqMLz97GeXp4J3fbEdNKbla7V6ar0xJuBqYOCH/jxtRf0fMAtvYWfhoTVHfH03hU4TK20ot//s65IdznL7q2RPUN/jAYfD0sexLLisEqv22phWGN2V1P4BG5+MXbqrWpB8tk9aK0hgxQkZ5y0gkRExUnOo6iI70gwXMd7wkU6TyuR1DAAAADMIfBQRf9RzUW7deSGfrwJeim6vOz/Nwp3WU1u9CrxPr9vR0O++FEpUzY8ffhhlTEi3twdmWrX5ufFbzAU+s3MYqTGy+Ail+2lJ9IzM1L+wDb/lJZhl2yq0DIr8eqEQA/XabBoEvOc8nuwz1wjw7MQHZ5jAVCHBYoEABnFoTI84Jk6i7RMGambfjZYCkIYoERSIVNeX2Qjf810UF2u4GM9We801hFq20Kq2vQQjmoElpTEs4u6wz4BXvghxULomXuo6pgAzX/m+GInPOM+AAAA0SHxVEX/Uc1Fu3Xkhn68CXpHHluZAbPCd1lNbvQq8T6/b1qUasVGiV8OoHqT5OQX1XnlHFG+uOJpRdZ9kPXyZw/DT7qZwzCJYE3/M2frIJhhKKVX4XpVBxmOmInMA3kr7k+CdzFETDT55RqK3NagkBuHBuBQ9X7uihmo7iORfrkcwGFtgV1dnJYPUe4q2qaEUL1PbvEvyF/ExTf7uf0/8zHPAfHVo02tvCEY3w1Hp9KHCVy9b0pCvM///bcYRCgEbt1AufnSP4Ak7bt8Pa9sCkvgAAABTCHyWEX/Vr/oue8DCKQ0GrH5j3VfrTjyGLVbtngrB2BMeHA4JkFIkwoiKoVuQQYdgMDCG97FakFd87ux80b6H//QtwZfdH1avQVrP/2lvRi4T9/FW9NaR28XCG5tmG7bxA776LHQ4NaV8PFWpnfvWwvH6/eacsn9voWEcE4hqchu8eMBQdMJEoYBxiRND5tzDJ4HNQSATmr5qN4Jva82kAA+y5ycAouYXJpIwCPL01zq5RN2n8zUoIDQV0W9ki9En00cF54yF6ac9f97ZAJ1AxxM5PwoR3JlPCoYnEV1LFDubY1SSsbUhHhVYs86G3jKUfio9PQYOMLx8chYei8zfrEcOPeJqF/eyvyqtpPzW7LyngE4BYcMawzi2r5cL0VwtcwuFDE1uScdov7FFVNXippgcNDgqrFuLc52ltvkpdKKKnJ9JzXT1lZJtFUsAAAA6iHzXEX/Uc1Fu3Xkhn68DeXkceW5kBs8J3WU1u9CrxPr9vGCJTUBE2bHj8Tek8s4hrgZpVadqIhg34ViWTkZq+cCWSTL6cN7w8rL/ZkQmcQj1brEfAUEvzW6qcP/UpiAni99EOzOYL+H/m6mWKBkUrAnEuADB1weN8vqZ5TiqaecLkqqbwcPwrOIHWhVA9gAEIJTWZHlLyBgW8X2dEP//752qoZIR21/FYMZu3UEeaBOoYOcumFDaS2NJcagTPO1mKS1Sl2g4gLnQCSn82w3Ft2Vq8zfz+gGnRqF29KNQVMBwZCPbmJgsKCTKg==';

Uint8List get _probeMp4 => base64Decode(_kProbeMp4Base64);

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

void main() {
  // The video plugin goes through a MethodChannel — needs the binding.
  TestWidgetsFlutterBinding.ensureInitialized();

  // =========================================================================
  // generateThumbnail — image
  // =========================================================================
  group('generateThumbnail (image)', () {
    test('returns JPEG bytes for valid JPEG image', () async {
      final thumb = await generateThumbnail(_createJpeg(8, 6), 'image/jpeg');

      expect(thumb, isNotNull);
      expect(thumb!.length, greaterThan(0));
      // JPEG magic bytes
      expect(thumb[0], 0xFF);
      expect(thumb[1], 0xD8);
    });

    test('returns JPEG bytes for valid PNG image', () async {
      final thumb = await generateThumbnail(_createPng(8, 6), 'image/png');

      expect(thumb, isNotNull);
      expect(thumb!.length, greaterThan(0));
      // Should be re-encoded as JPEG
      expect(thumb[0], 0xFF);
      expect(thumb[1], 0xD8);
    });

    test('returns JPEG bytes for animated GIF (first frame)', () async {
      final thumb =
          await generateThumbnail(_createAnimatedGif(12, 12), 'image/gif');

      expect(thumb, isNotNull);
      expect(thumb![0], 0xFF);
      expect(thumb[1], 0xD8);

      // First frame is red — probe, not just magic bytes.
      final decoded = _decode(thumb);
      final pixel = _centerPixel(decoded);
      expect(pixel.r, greaterThan(150));
      expect(pixel.b, lessThan(120));
    });

    test('returns null for PDF MIME type', () async {
      final pdfBytes = Uint8List.fromList([0x25, 0x50, 0x44, 0x46]); // %PDF
      final thumb = await generateThumbnail(pdfBytes, 'application/pdf');
      expect(thumb, isNull);
    });

    test('returns null for text/plain', () async {
      final textBytes = Uint8List.fromList('hello world'.codeUnits);
      final thumb = await generateThumbnail(textBytes, 'text/plain');
      expect(thumb, isNull);
    });

    test('returns null for application/octet-stream', () async {
      final bytes = Uint8List(100);
      final thumb =
          await generateThumbnail(bytes, 'application/octet-stream');
      expect(thumb, isNull);
    });

    test('returns null for corrupted image bytes', () async {
      final badBytes = Uint8List.fromList([0x00, 0x01, 0x02, 0xFF]);
      final thumb = await generateThumbnail(badBytes, 'image/jpeg');
      expect(thumb, isNull);
    });

    test('returns null for HEIC (no decoder in package:image)', () async {
      // ftyp box with heic brand — real HEIC signature; package:image has
      // no HEIC decoder, so even the full file returns null.
      final heicBytes = Uint8List.fromList([
        0x00, 0x00, 0x00, 0x18, 0x66, 0x74, 0x79, 0x70, // ....ftyp
        0x68, 0x65, 0x69, 0x63, 0x00, 0x00, 0x00, 0x00, // heic....
        0x68, 0x65, 0x69, 0x63, 0x6D, 0x69, 0x66, 0x31, // heicmif1
      ]);
      final thumb = await generateThumbnail(heicBytes, 'image/heic');
      expect(thumb, isNull);
    });

    test('thumbnail size is reasonable (<< 100 KB)', () async {
      final thumb = await generateThumbnail(_createJpeg(8, 6), 'image/jpeg');

      expect(thumb, isNotNull);
      // A 256px JPEG at quality 0.7 should be well under 100 KB.
      expect(thumb!.length, lessThan(100 * 1024));
    });
  });

  // =========================================================================
  // Scaling — verified by decoding the output (no browser APIs)
  // =========================================================================
  group('scaling', () {
    test('landscape image is scaled to fit max dimension', () async {
      final thumb = await generateThumbnail(_createPng(800, 400), 'image/png');
      final decoded = _decode(thumb!);

      // Aspect ratio: 800:400 = 2:1, max dim 256 → 256×128
      expect(decoded.width, 256);
      expect(decoded.height, 128);
    });

    test('portrait image is scaled to fit max dimension', () async {
      final thumb = await generateThumbnail(_createPng(200, 600), 'image/png');
      final decoded = _decode(thumb!);

      // Aspect ratio: 200:600 = 1:3, max dim 256 → 85×256
      expect(decoded.height, 256);
      expect(decoded.width, lessThan(256));
      expect(decoded.width, 85);
    });

    test('small image is NOT upscaled', () async {
      final thumb = await generateThumbnail(_createPng(50, 50), 'image/png');
      final decoded = _decode(thumb!);

      // Should stay 50×50 (not be upscaled).
      expect(decoded.width, 50);
      expect(decoded.height, 50);
    });

    test('square large image is scaled correctly', () async {
      final thumb = await generateThumbnail(_createPng(512, 512), 'image/png');
      final decoded = _decode(thumb!);

      // 512×512 → 256×256
      expect(decoded.width, 256);
      expect(decoded.height, 256);
    });
  });

  // =========================================================================
  // Pixel probes — the case the dart:ui pipeline returned white
  // =========================================================================
  group('pixel probes (sub-256 images)', () {
    test('small JPEG keeps real pixels (not white)', () async {
      final source = img.ColorRgb8(220, 40, 40);
      final thumb =
          await generateThumbnail(_createJpeg(8, 6, color: source), 'image/jpeg');
      final pixel = _centerPixel(_decode(thumb!));

      expect(pixel.r, greaterThan(150));
      expect(pixel.g, lessThan(110));
      expect(pixel.b, lessThan(110));
    });

    test('small PNG keeps real pixels (not white)', () async {
      final source = img.ColorRgb8(40, 40, 220);
      final thumb =
          await generateThumbnail(_createPng(50, 50, color: source), 'image/png');
      final pixel = _centerPixel(_decode(thumb!));

      expect(pixel.b, greaterThan(150));
      expect(pixel.r, lessThan(110));
      expect(pixel.g, lessThan(110));
    });
  });

  // =========================================================================
  // generateThumbnail — video
  // =========================================================================
  group('generateThumbnail (video)', () {
    setUp(() {
      videoSourceCreatedCount = 0;
      videoSourceDisposedCount = 0;
    });

    test('returns null for video bytes over 200 MiB limit', () async {
      final largeBytes = Uint8List(kVideoThumbnailMaxBytes + 1);
      final thumb = await generateThumbnail(largeBytes, 'video/mp4');
      expect(thumb, isNull);

      // Cap is checked before a source is created — nothing to dispose.
      expect(videoSourceCreatedCount, 0);
      expect(videoSourceDisposedCount, 0);
    });

    test('returns null for small but invalid video bytes', () async {
      // 100 bytes of garbage is not a valid video → should return null, not
      // crash.
      final badBytes = Uint8List.fromList(
        List.generate(100, (i) => i % 256),
      );
      final thumb = await generateThumbnail(badBytes, 'video/mp4');
      expect(thumb, isNull);

      // The source was created and disposed even on failure.
      expect(videoSourceCreatedCount, 1);
      expect(videoSourceDisposedCount, 1);
    });

    test('returns null for empty video bytes', () async {
      final empty = Uint8List(0);
      final thumb = await generateThumbnail(empty, 'video/mp4');
      expect(thumb, isNull);

      expect(videoSourceCreatedCount, 1);
      expect(videoSourceDisposedCount, 1);
    });

    // Browser-only: real video decode + frame capture needs a video element.
    test(
      'real MP4 → JPEG thumbnail of the ~1s frame, source disposed',
      skip: !kIsWeb,
      () async {
        // Web tests don't run the plugin registrant — register by hand.
        registerVideoThumbnailForTest();
        videoSourceCreatedCount = 0;
        videoSourceDisposedCount = 0;
        final mp4 = _probeMp4;

        // Reference: first frame (timeMs 1 — avoids the no-seek case of
        // exactly 0, which never fires onSeeked).
        final firstFrameSource = await createVideoSource(mp4, 'video/mp4');
        final firstFrame = await VideoThumbnail.thumbnailData(
          video: firstFrameSource.uri.toString(),
          imageFormat: ImageFormat.JPEG,
          maxWidth: 0,
          maxHeight: 0,
          timeMs: 1,
          quality: 90,
        ).timeout(const Duration(seconds: 10));
        firstFrameSource.dispose();

        final thumb = await generateThumbnail(mp4, 'video/mp4');
        expect(thumb, isNotNull);
        expect(thumb![0], 0xFF);
        expect(thumb[1], 0xD8);

        // Both sources created during this test were disposed.
        expect(videoSourceCreatedCount, 2);
        expect(videoSourceDisposedCount, 2);

        final decoded = _decode(thumb);
        // 160×90 source, no upscale: stays 160×90.
        expect(decoded.width, 160);
        expect(decoded.height, 90);

        // Not black.
        final center = _centerPixel(decoded);
        expect(center.r + center.g + center.b, greaterThan(60));

        // ~1s frame, not the first frame: the moving white block covers the
        // center at t=1s (frame 12, x=60..90) but not at t≈0.
        final firstCenter = _centerPixel(_decode(firstFrame));
        final rDiff = (center.r - firstCenter.r).abs();
        expect(rDiff, greaterThan(80));
      },
    );
  });

  // =========================================================================
  // Video thumbnail — path-based (original file, no cap)
  // =========================================================================
  group('video thumbnail from path', () {
    setUp(() {
      videoSourceCreatedCount = 0;
      videoSourceDisposedCount = 0;
      // No-op on VM; chrome tests hang on plugin channels without it.
      registerVideoThumbnailForTest();
    });

    test('inaccessible path → null, no crash, no VideoSource', () async {
      final thumb = await getThumbnailVideoFromPath('/nonexistent/nope.mp4');
      expect(thumb, isNull);

      // The path route never builds a VideoSource — nothing to dispose.
      expect(videoSourceCreatedCount, 0);
      expect(videoSourceDisposedCount, 0);
    });

    // Browser-only: real video decode + frame capture needs a video element.
    test(
      'blob URL path → thumbnail of the ~1s frame, no VideoSource',
      skip: !kIsWeb,
      () async {
        // Real blob URL over the probe MP4 — the same shape image_picker
        // delivers on web. Created before resetting the counters, so the
        // assertions below attribute only the thumbnail call.
        final source = await createVideoSource(_probeMp4, 'video/mp4');
        videoSourceCreatedCount = 0;
        videoSourceDisposedCount = 0;

        final thumb = await getThumbnailVideoFromPath(source.uri.toString());
        expect(thumb, isNotNull);
        expect(thumb![0], 0xFF);
        expect(thumb[1], 0xD8);

        // The path route never builds a VideoSource.
        expect(videoSourceCreatedCount, 0);
        expect(videoSourceDisposedCount, 0);

        source.dispose();
        expect(videoSourceDisposedCount, 1);

        final decoded = _decode(thumb);
        // 160×90 source, no upscale: stays 160×90.
        expect(decoded.width, 160);
        expect(decoded.height, 90);

        // Not black.
        final center = _centerPixel(decoded);
        expect(center.r + center.g + center.b, greaterThan(60));
      },
    );

    test(
      'bytes over the cap + path → thumbnail (size never checked)',
      skip: !kIsWeb,
      () async {
        final source = await createVideoSource(_probeMp4, 'video/mp4');

        // 200 MiB + 1 — the exact size that kills the bytes route. The path
        // route must never look at these bytes.
        final largeBytes = Uint8List(kVideoThumbnailMaxBytes + 1);

        final thumb = await generateThumbnail(
          largeBytes,
          'video/mp4',
          sourcePath: source.uri.toString(),
        );
        expect(thumb, isNotNull);

        source.dispose();
      },
    );
  });
}
